function Hd = DChebyshevTypeII_LowPass
%DCHEBYSHEVTYPEII_LOWPASS 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 10-Jun-2022 15:23:02

% Chebyshev Type II Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in kHz.
load('START.mat','FC');
load('AnalogCircuitProcessing_1.mat','FS');

Fpass = (FC/2)/1000; % Passband Frequency
Fstop = 2*Fpass;         % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 60;          % Stopband Attenuation (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, FS/1000);
Hd = design(h, 'cheby2', 'MatchExactly', match);

% [EOF]
