function Hd = DChebyshevTypeII_BandPass
%DCHEBYSHEVTYPEII_BANDPASS 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 10-Jun-2022 11:21:24

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in kHz.
load('START.mat','FC','BW');
load('AnalogCircuitProcessing_1.mat','FS');

Fpass1 = (FC-BW/2)/10^3-10;  % First Passband Frequency
Fpass2 = (FC+BW/2)/10^3+10;  % Second Passband Frequency
Fstop1 = Fpass1-10;   % First Stopband Frequency
Fstop2 = Fpass2+10;   % Second Stopband Frequency
Astop1 = 60;          % First Stopband Attenuation (dB)
Apass  = 0.1;         % Passband Ripple (dB)
Astop2 = 60;          % Second Stopband Attenuation (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, FS/1000);
Hd = design(h, 'cheby2', 'MatchExactly', match);

% [EOF]
